version: "1"

tasks:
  build:
    desc: Build app
    cmds:
    - GOFLAGS=-mod-mod go build -o bin/go-bot-discord main.go
  
  run:
    desc: Run bot
    cmds:
    - GOFLAGS=-mod=mod go run main.go -t %BOT_TOKEN%
  
  bot:
    desc: Execute bot
    cmds:
    - ./bin/go-bot-discord -t %BOT_TOKEN%